version: "3.7"

networks:
  test-bench.db.network:
    driver: bridge
  test-bench.srv.network:
    driver: bridge

volumes:
  postgresql: {}
  postgresql_data: {}

services:

#  zookeeper:
#    image: wurstmeister/zookeeper
#    networks:
#      - test-bench.srv.network
#    ports:
#      - "2181:2181"
#      -
#  kafka:
#    build: .
#    networks:
#      - test-bench.srv.network
#    ports:
#      - "9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock


  postgres:
    build: ../postgres
    container_name: pg01
    networks:
      - test-bench.db.network
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data
      -
  user:
    build: ../user
    container_name: uss01
    links:
      - "postgres"
    depends_on:
      - postgres
    restart: always
    networks:
      - test-bench.srv.network
      - test-bench.db.network
    ports:
      - 8001:8080
