info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    ersion: @project.version@

spring:
  application:
    name: User Service
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler.probability: 1
  datasource:
    url: jdbc:postgresql://postgres:5432/users
    username: admin
    password: password
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  jooq:
    sql-dialect: Postgres

management:
  metrics:
    enable:
      root: true
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    console: "%d %-5level %logger %msg%n"
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: INFO

---

spring:
  profiles: local
  datasource:
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: "ALWAYS"

