version: 2.1
jobs:
  build:
    docker:
      - image: maxur/openjdk11-postgesql
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx4096m
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: chmod -R 777 ./mvnw && ./mvnw dependency:go-offline -P check-dep
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  test:
    docker:
      - image: maxur/openjdk11-postgesql
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: chmod -R 777 ./mvnw && ./mvnw dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: chmod -R 777 ./mvnw && pg_ctl start -D /var/lib/postgresql/data -l /var/lib/postgresql/log.log && ./mvnw verify -X -P jacoco
      - run:
          name: Upload Coverage Results
          command: |
            set -e
            REPO_TOKEN=${<< parameters.repo_token_env_var >>}
            if [ -z "${REPO_TOKEN}" ]; then
              # git@github.com:owner/repo.git
              REPO_NAME="${CIRCLE_REPOSITORY_URL##*:}"
              # owner/repo.git
              REPO_NAME="${REPO_NAME%%.git}"
              API_TOKEN=${<< parameters.api_token_env_var >>}
              REPO_TOKEN=$(curl -X GET "https://codecov.io/api/pub/gh/${REPO_NAME}/settings" -H "Authorization: token ${API_TOKEN:?}" | jq .repo.upload_token --raw-output)
            fi
            curl -s https://codecov.io/bash --show-error | bash -s -- \
              -f ./target/coverage-reports/jacoco-ut.exec \
              -t "${REPO_TOKEN}" \
              -Z || echo 'Codecov upload failed'

      - codecov/upload:
          file: ./target/coverage-reports/jacoco-ut.exec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test