version: 2
jobs:
  build:
    docker:
      - image: maxur/openjdk11-postgesql
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx4096m
    parallelism: 2
    resource_class: large
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  test1:
    docker:
      - image: maxur/openjdk11-postgesql
    working_directory: ~/repo
    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn -pl maxur-mserv-core dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn verify -X
  #      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1