version: 2.1
jobs:
  build:
    docker:
      - image: maxur/openjdk11-postgesql
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx4096m
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: chmod -R 777 ./mvnw && ./mvnw dependency:go-offline -P check-dep
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  test:
    docker:
      - image: maxur/openjdk11-postgesql
        user: postgres
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: chmod -R 777 ./mvnw && ./mvnw dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: chmod -R 777 ./mvnw && pg_ctl start -D /var/lib/postgresql/data -l /var/lib/postgresql/log.log && ./mvnw verify -X -P jacoco
      - run:
          name: Upload Coverage Results
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test