name: Auto Merge

on:
  check_suite:
    types:
      - completed

jobs:
  merge-me:
    name: Auto Merge
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        uses: ridedott/merge-me-action@master
        with:
          uses: ridedott/merge-me-action@master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
