name: create-pull-request

on:
  push:
    branches: 
    - dev 
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ""                     # If blank, default: triggered branch
          destination_branch: "master"          # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into master"
          pr_body: ":crown: *An automated PR*"  # Full markdown support, requires pr_title to be set
          pr_label: "auto"                      # Comma-separated list (no spaces)
          github_token: ${{ secrets.GITHUB_TOKEN }}