name: merge-pull-request

on:
  check_suite:
    types:
      - completed
    branches:
      - dev
      - master
jobs:
  mergepal-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@v0.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          method: squash
